package service

import "errors"

var (
	ErrIdentityAlreadyExists    = errors.New("identity already exists")
	ErrUsernameAlreadyExists    = errors.New("username already exists")
	ErrEmailAlreadyExists       = errors.New("email already exists")
	ErrInvalidCredentials       = errors.New("invalid credentials")
	ErrInvalidProfile           = errors.New("invalid user profile")
	ErrProfileIncomplete        = errors.New("user profile incomplete")
	ErrEmailRequired            = errors.New("email is required")
	ErrInviteCodeRequired       = errors.New("invite code required")
	ErrInviteCodeInvalid        = errors.New("invite code invalid or expired")
	ErrInviteCodeExhausted      = errors.New("invite code usage exhausted")
	ErrRefreshTokenInvalid      = errors.New("refresh token invalid or revoked")
	ErrUserNotFound             = errors.New("user not found")
	ErrUserDisabled             = errors.New("user is disabled or banned")
	ErrEmailNotVerified         = errors.New("email is not verified")
	ErrEmailVerifyDisabled      = errors.New("email verification is disabled")
	ErrEmailVerifyToken         = errors.New("email verification token invalid or expired")
	ErrEmailVerifyTokenRequired = errors.New("email verification token is required")
	ErrIdentityNotFound         = errors.New("identity not found")
	ErrCannotUnbindLast         = errors.New("cannot unbind last identity")
	ErrIdentityNotOwned         = errors.New("identity does not belong to this user")
	ErrUnsupportedIdentity      = errors.New("unsupported identity type for direct login")
	ErrOIDCClientNotFound       = errors.New("oidc client not found")
	ErrOIDCClientExists         = errors.New("oidc client already exists")
	ErrOIDCClientInvalid        = errors.New("invalid oidc client input")
)
